# Generated by Django 3.2 on 2021-05-12 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('headline', models.CharField(max_length=1000)),
                ('industry', models.CharField(max_length=100)),
                ('business_type', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('province', models.CharField(blank=True, max_length=200, null=True)),
                ('surburb_township', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('Manucipality', models.CharField(max_length=1000)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('cell', models.IntegerField(null=True)),
                ('land_line', models.IntegerField(null=True)),
                ('fax_number', models.IntegerField(null=True)),
                ('code', models.IntegerField(null=True)),
                ('contact_person', models.CharField(max_length=1000)),
                ('business_established_date', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True, default='no bio...', max_length=300)),
                ('CEO', models.CharField(max_length=1000)),
                ('email_address', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('avatar', models.ImageField(default='avatar.png', upload_to='avatars/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(upload_to='uploads/')),
                ('connections', models.ManyToManyField(blank=True, related_name='connections', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('send', 'send'), ('accepted', 'accepted')], max_length=8)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='profiles.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='profiles.profile')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
