# Generated by Django 3.2 on 2021-05-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_relationship_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
